[workspace]
resolver = "2"

members = ["serde_valid", "serde_valid_derive", "serde_valid_literal"]

[workspace.package]
edition = "2021"
version = "0.11.2"
authors = ["yassun4dev <yassun4dev@outlook.com>"]
keywords = ["validation", "serde", "json_schema"]

[workspace.dependencies]
regex = "^1.6"
paste = "^1.0"
