[package]
name = "serde_valid"
version = "0.1.0"
authors = ["yassun4dev <yassun4dev@outlook.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/yassun4dev/serde_valid.git"
description = "JSON Schema based validation tool using with serde."
readme = "README.md"
categories = ["validation"]
keywords = ["validation", "serde", "json_schema"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "^0.10"
num-traits = "^0.2"
once_cell = "^1.7"
regex = "^1.4"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
serde_toml = { package = "toml", version = "^0.5", optional = true }
serde_valid_derive = { version = "0.1.0", path = "derive" }
serde_yaml = { version = "^0.8", optional = true }
thiserror = "^1.0"
unicode-segmentation = "^1.7"

[workspace]
members = ["derive"]

[features]
default = []
toml = ["serde_toml"]
yaml = ["serde_yaml"]
