[package]
name = "serde_valid"
version = "0.1.0"
authors = ["安谷尚人 <yasutani_naoto@uniquevision.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "^1.0"
serde_valid_derive = { version = "0.1.0", path = "../serde_valid_derive", optional = true }
num-traits = "^0.2"
unicode-segmentation = "^1.7"

[features]
derive = ["serde_valid_derive"]
