[package]
name = "serde_valid"
license = "MIT"
repository = "https://github.com/yassun4dev/serde_valid.git"
description = "JSON Schema based validation tool using with serde."
categories = ["encoding"]
authors.workspace = true
edition.workspace = true
keywords.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = { version = "^1.9", features = ["serde"] }
itertools = "^0.10"
jsonschema = { version = "^0.16", optional = true }
num-traits = "^0.2"
once_cell = "^1.7"
paste = "^1.0"
regex = "^1.4"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
serde_toml = { package = "toml", version = "^0.5", optional = true }
serde_valid_derive = { version = "0.10.0", path = "../serde_valid_derive" }
serde_valid_literal = { version = "0.10.0", path = "../serde_valid_literal" }
serde_yaml = { version = "^0.9", optional = true }
thiserror = "^1.0"
unicode-segmentation = "^1.7"

[features]
default = []
toml = ["serde_toml"]
yaml = ["serde_yaml"]
flatten = ["jsonschema"]
